const PRICE_CONFIG = {
  URL: "https://gasprice.kapook.com/",
  SELECTOR: {
    ptt: {
      gasoline_95: "เบนซิน 95",
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      gasohol_e85: "แก๊สโซฮอล์ E85",
      diesel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
      premium_diesel: "ดีเซลพรีเมียม",
      superpower_gasohol_95: "แก๊สโซฮอล์ 99 พรีเมียม",
      ngv: "แก๊ส NGV",
    },
    bcp: {
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      gasohol_e85: "แก๊สโซฮอล์ E85",
      disel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
      premium_diesel: "ดีเซลพรีเมียม",
      premium_gasohol_95: "แก๊สโซฮอล์ 95 พรีเมียม",
    },
    shell: {
      gasohol_95: "เชลล์ ฟิวเซฟ แก๊สโซฮอล์ 95",
      gasohol_91: "เชลล์ ฟิวเซฟ แก๊สโซฮอล์ 91",
      gasohol_e20: "เชลล์ ฟิวเซฟ แก๊สโซฮอล์ E20",
      vpower_gasohol_95: "เชลล์ วี-เพาเวอร์ แก๊สโซฮอล์ 95",
      vpower_diesel: "เชลล์ วี-เพาเวอร์ ดีเซล",
      fuelsafe_diesel: "เชลล์ ฟิวเซฟ ดีเซล",
      diesel_b20: "เชลล์ ดีเซล B20",
    },
    caltex: {
      gasoline_95: "เบนซิน 95",
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      diesel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
      premium_diesel: "ดีเซลพรีเมียม",
    },
    irpc: {
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      diesel: "ดีเซล B7",
    },
    pt: {
      gasoline_95: "เบนซิน 95",
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      diesel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
    },
    susco: {
      gasoline_95: "เบนซิน 95",
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      diesel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
    },
    pure: {
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      diesel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
    },
    susco_dealers: {
      gasoline_95: "เบนซิน 95",
      gasohol_95: "แก๊สโซฮอล์ 95",
      gasohol_91: "แก๊สโซฮอล์ 91",
      gasohol_e20: "แก๊สโซฮอล์ E20",
      diesel: "ดีเซล B7",
      diesel_b20: "ดีเซล B20",
    },
  },
};

export default PRICE_CONFIG;
